In [1]:
import numpy as np


In [2]:
x=np.array([[0],[1],[2]])
y=np.array([[3,4,5]])

In [3]:
print(x)

[[0]
 [1]
 [2]]


In [4]:
print(y)

[[3 4 5]]


In [5]:
x+y

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [6]:
x.shape

(3, 1)

In [7]:
y.shape

(1, 3)

In [15]:
(x*y).shape

(3, 3)

In [17]:
x*y

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

In [16]:
# to simulate this operation
shappe=(3,3)
out=np.empty(shappe,dtype=int)
N0,N1=shappe
for i in range(N0): # operate from higher level and loop in lower level # like all data structure fuctioned
    for j in range(N1):
        # the demension y just have one element we replace 1 to zero; or any 1 in demension from shape to zero in loop
        out[i,j]=x[i,0]*y[0,j]
print(out)

[[ 0  0  0]
 [ 3  4  5]
 [ 6  8 10]]


In [9]:
z=np.array([1,2,3])
z.shape ## we miss one [] we can append 1 as (1,3,) or (1,3) append has to be ahead of the array 

(3,)

In [10]:
# we are not allow to reorder the axis or index to check the compatability on matricy multiplications

In [11]:
# example1.sahpe == (1,2,3,4,7,1,8)
#example2.shape==(4,1,1,8)
#still compitable 
#how when we do example2.sahpe == (1,1,1,4,1,7,8) # after we pre append 1
# the out come will be (1,2,3,4,7,7,8)

In [19]:
# another example
x=np.array(([[[0,1,2],
           [3,4,5],
           [6,7,8]],
             [[9,10,11],
             [12,13,14],
             [15,16,17]]])) # shape (2,3,3)
y=np.array([1,10,100]) # shape(3,)
print(x+y)

[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]


In [20]:
# after add 1 final shape should be (2,3,3)

In [21]:
shappe=(2,3,3)
out=np.empty(shappe,dtype=int)
N0,N1,N2=shappe
for i in range (N0): # From the outter to inner
    for j in range(N1):
        for k in range(N2):
            out[i,j,k]=x[i,j,k]+y[k] # since we put replacement 1 will be (1,1,3)
            #hence 3 is k index for the demension
print(out)

[[[  1  11 102]
  [  4  14 105]
  [  7  17 108]]

 [[ 10  20 111]
  [ 13  23 114]
  [ 16  26 117]]]
